apiVersion: v2
name: common-chart
description: Общие шаблоны для всех приложений
type: library        # library — чарт нельзя деплоить напрямую, только использовать как зависимость
version: 0.2.0
appVersion: "1.0.0"