apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-map
  namespace: {{ .Release.Namespace }}
data:
  {{- range $k, $v := .Values.envs.configMap }}
  {{ $k }}: "{{ $v }}"
  {{- end }}