apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- range .Values.labels }}
    {{ .name }}: "{{ .value }}"
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- range .Values.labels }}
      {{ .name }}: "{{ .value }}"
      {{- end }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        {{- range .Values.labels }}
        {{ .name }}: "{{ .value }}"
        {{- end }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.name }}"
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.health }}
              port: {{ .Values.backend.port }}
            failureThreshold: 12
            timeoutSeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.health }}
              port: {{ .Values.backend.port }}
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.ready }}
              port: {{ .Values.backend.port }}
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config-map
            - secretRef:
                name: {{ .Chart.Name }}-secret