apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-monitor
  labels:
    release: {{ .Values.monitoring.release }}
spec:
  selector:
    matchLabels:
      {{- range .Values.labels }}
      {{ .name }}: "{{ .value }}"
      {{- end }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s